spring.application.name=pizzariaatlas

# SQL Server Configuration

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=pizzariaatlasdb;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=@ITB123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


# Explicações

# encrypt: (true ) Requer criptografia do cliente (false) não requer criptografia do cliente
# trustServerCertificate: (true) Instrui o aplicativo cliente a ignorar a validação do certificado SSL/TSL do servidor

# spring.jpa.hibernate.ddl-auto
   # none: Banco de dados e tabelas devem ser criados com antecedência
   # update: Banco de dados deve ser criado com antecedência, tabelas podem ser criadas com antecedência, as tabelas
   #         são atualizadas pelo código (model )
   # create-drop: Banco de dados deve ser criado com antecedência, as tabelas são criadas automaticamente pelo código (model)
   #          serão excluídas toda vez que o servidor é "desligado" (interrompido)
   # create: Banco de dados deve ser criado com antecedência, quando o servidor "sobe", as tabelas são recriadas, as tabelas
   #          não serão excluídas quando o servidor é interrompido.